### ISSUE TITLE
Expose escape sequences as nodes

### ISSUE THREAD

**Issue by Janfel** [MunifTanjim/tree-sitter-lua#9]
Hi, can you please have escape sequences (`\n`, `\t`, ...) be parsed into their own nodes so they can be highlighted? Some other parsers like [tree-sitter-c](https://github.com/tree-sitter/tree-sitter-c) already do this. You can find the list of valid escape sequences for Lua 5.4 under https://www.lua.org/manual/5.4/manual.html#3.1

**Comment by GabrielFrigo4** [comment]
When I create a lua file in neovim, it highlights the \n, \t... but when I save and open again it goes back to 'normal'
 - When it is created using "nvim teste3.lua" in the cmd. File teste3.lua doesn't exist:
![image](https://user-images.githubusercontent.com/66432268/198908342-c9e477a0-1594-4e33-9f3a-117923566f5f.png)
 - When it is loaded using "nvim test3.lua" in the cmd. File teste3.lua already created:
![image](https://user-images.githubusercontent.com/66432268/198908363-bd6c3b3c-79ed-4e9c-aca7-cb2077e0bcc2.png)
don't know if this is caused by a wrong configuration of my neovim but apparently it's not.
